name: limit
description: "Persistent across sessions, no manual storage needed. Easily manage cooldowns and rate limits with one-line."
version: 1.0.7
homepage: https://github.com/jozzzzep/limit
repository: https://github.com/jozzzzep/limit
issue_tracker: https://github.com/jozzzzep/limit/issues
topics:
  - rate-limiter
  - cooldown
  - rate-limit
  - persistence
  - easy-to-use

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  prf: ^2.3.1
  synchronized: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  shared_preferences_platform_interface: ^2.4.1
  shared_preferences: ^2.4.1
